import {
  CollectionScenario,
  DisposalScenario,
  LHSScenario,
  CertifierScenario,
  Badge,
  LeaderboardEntry,
} from './types';

export const INITIAL_BADGES: Badge[] = [
  {
    id: 'geometrician',
    name: 'The Geometrician',
    icon: '📐',
    description: 'Accurately measured and certified trucks with dog houses, sideboards, and wheel well deductions.',
    unlocked: false,
    progress: 0,
    target: 5,
  },
  {
    id: 'arborist_assassin',
    name: 'The Arborist Assassin',
    icon: '🪵',
    description: 'Correctly identified pre-existing dead trees (pest/rot) and saved FEMA from paying for ineligible deferred maintenance.',
    unlocked: false,
    progress: 0,
    target: 5,
  },
  {
    id: 'gatekeeper',
    name: 'The Gatekeeper',
    icon: '🛑',
    description: 'Caught trucks "hauling air" or soaking C&D at the TDSR disposal tower and slashed load calls.',
    unlocked: false,
    progress: 0,
    target: 5,
  },
  {
    id: 'trespass_denied',
    name: 'Trespass Denied',
    icon: '🚫',
    description: 'Stopped crews from crossing sidewalks into private property without an executed Right-of-Entry (ROE).',
    unlocked: false,
    progress: 0,
    target: 5,
  },
  {
    id: 'fema_auditor_shield',
    name: 'FEMA Public Assistance Shield',
    icon: '🛡️',
    description: 'Maintained zero cost de-obligations across 10 consecutive field calls.',
    unlocked: false,
    progress: 0,
    target: 10,
  },
];

export const INITIAL_LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, name: 'Chief Auditor Marcus Vance', roleTitle: 'Senior PA Lead Specialist', taxpayerSaved: 1425800, accuracy: 99.4, badgesCount: 5 },
  { rank: 2, name: 'Elena Rostova, PE', roleTitle: 'USACE Tower Supervisor', taxpayerSaved: 984200, accuracy: 98.1, badgesCount: 4 },
  { rank: 3, name: 'Carlos "Iron-Eye" Mendoza', roleTitle: 'Certified Tree Arborist / LHS', taxpayerSaved: 742100, accuracy: 96.8, badgesCount: 4 },
  { rank: 4, name: 'Sarah Chen, CFM', roleTitle: 'ADMS Fleet Certifier', taxpayerSaved: 512900, accuracy: 95.2, badgesCount: 3 },
  { rank: 5, name: 'Debris Cadet (You)', roleTitle: 'Frontline Debris Monitor', taxpayerSaved: 0, accuracy: 100, badgesCount: 0, isPlayer: true },
  { rank: 6, name: 'Jake Miller', roleTitle: 'Junior Field Monitor', taxpayerSaved: 185000, accuracy: 88.5, badgesCount: 1 },
];

export const COLLECTION_SCENARIOS: CollectionScenario[] = [
  {
    id: 'col-1',
    truckPlacard: 'TRK-842 (Kenworth T880)',
    capacityCY: 40,
    streetAddress: '1402 Gulfview Drive, Public ROW Curb',
    isPublicROW: true,
    hasROE: false,
    pileVisual: 'Fresh fallen pine tree trunks, severed live oak limbs, and shredded palm fronds stacked neatly on the curb between asphalt edge and utility poles.',
    primaryDebris: 'Vegetative',
    contamination: null,
    driverBribeOrPressure: 'Crew Boss: "Hey Monitor! We got 3 more streets before dark. Stamp this clean vegetative ticket so the loader can drop it in!"',
    timeLimitSec: 28,
    value: 6400,
  },
  {
    id: 'col-2',
    truckPlacard: 'TRK-219 (Mack Granite)',
    capacityCY: 45,
    streetAddress: '883 Azalea Court, Private Front Lawn (Past Sidewalk)',
    isPublicROW: false, // The PPDR Trap!
    hasROE: false,
    pileVisual: 'Huge pile of storm branches piled 15 feet inside private manicured lawn beyond sidewalk. Property owner is waving hands frantically.',
    primaryDebris: 'Vegetative',
    contamination: null,
    driverBribeOrPressure: 'Homeowner: "Please! The city loader is right here! Just scoop it from my yard! Crew boss says he will if you hit approve!"',
    timeLimitSec: 25,
    value: 9200,
  },
  {
    id: 'col-3',
    truckPlacard: 'TRK-504 (Peterbilt 389)',
    capacityCY: 50,
    streetAddress: '412 Harbor Blvd, Commercial Strip Curb',
    isPublicROW: true,
    hasROE: false,
    pileVisual: 'Smashed drywall, 2x4 framing studs, corrugated metal roofing, but wait! A pile of rotting kitchen garbage bags and household trash is thrown right on top.',
    primaryDebris: 'C&D',
    contamination: 'Ineligible Garbage',
    driverBribeOrPressure: 'Loader Operator: "Come on boss, it’s mostly sheetrock and studs! FEMA will never notice two bags of normal trash!"',
    timeLimitSec: 25,
    value: 8500,
  },
  {
    id: 'col-4',
    truckPlacard: 'TRK-108 (Freightliner M2)',
    capacityCY: 35,
    streetAddress: '2305 Magnolia Avenue, ROW Swale',
    isPublicROW: true,
    hasROE: false,
    pileVisual: 'Split vegetative tree crowns mixed with smashed gypsum board, asphalt shingles, and insulation blankets.',
    primaryDebris: 'Vegetative',
    contamination: 'C&D', // Mixed load violation!
    driverBribeOrPressure: 'Driver: "It’s a combo load! Tag it as Vegetative so we don’t have to drive all the way to the C&D landfill!"',
    timeLimitSec: 22,
    value: 7800,
  },
  {
    id: 'col-5',
    truckPlacard: 'TRK-771 (Western Star 49X)',
    capacityCY: 60,
    streetAddress: '5501 Ocean Boulevard, Stormwater Easement',
    isPublicROW: true,
    hasROE: false,
    pileVisual: 'Storm-damaged refrigerators, washing machines, freezers, and water heaters with refrigerant lines intact.',
    primaryDebris: 'White Goods',
    contamination: null,
    driverBribeOrPressure: 'Scrap Contractor: "White Goods load ready for freon recovery depot certification. All certified on the public right of way!"',
    timeLimitSec: 26,
    value: 11000,
  },
  {
    id: 'col-6',
    truckPlacard: 'TRK-330 (Volvo VHD)',
    capacityCY: 40,
    streetAddress: '1904 St. Charles Way, Private Driveway',
    isPublicROW: false,
    hasROE: true, // Special approved PPDR with executed ROE!
    pileVisual: 'Catastrophic tree collapse blocking emergency access. Right of Entry (ROE #FL-2026-992) officially stamped and validated in GIS database.',
    primaryDebris: 'Vegetative',
    contamination: null,
    driverBribeOrPressure: 'City Inspector: "Monitor, this property has a verified FEMA ROE form on file due to critical health and safety hazard. Review ROE documentation carefully!"',
    timeLimitSec: 30,
    value: 12500,
  },
];

export const DISPOSAL_SCENARIOS: DisposalScenario[] = [
  {
    id: 'disp-1',
    ticketBarcode: 'TKT-99120-ROW',
    truckPlacard: 'TRK-442 (Dump Trailer 60 CY)',
    declaredDebris: 'Vegetative',
    originVerified: true,
    actualDebrisType: 'Vegetative',
    actualFillLevel: 85,
    isHaulingAir: false,
    isWaterWeight: false,
    driverClaimPercent: 100,
    driverDialogue: 'Driver: "Tower Boss, that’s 100% full! Bark and branches are spilling out over the sideboards! Stamp 100%!"',
    truckBedVisual: {
      texture: 'logs_leaves',
      hasHollowPockets: false,
      hasWaterPuddles: false,
      apparentFill: 95,
      trueFill: 85,
    },
    timeLimitSec: 24,
    value: 4800,
  },
  {
    id: 'disp-2',
    ticketBarcode: 'TKT-55102-ROW',
    truckPlacard: 'TRK-618 (High-Side Open Top 50 CY)',
    declaredDebris: 'Vegetative',
    originVerified: true,
    actualDebrisType: 'Vegetative',
    actualFillLevel: 45,
    isHaulingAir: true, // HAULING AIR FRAUD!
    isWaterWeight: false,
    driverClaimPercent: 90,
    driverDialogue: 'Driver: "Look at the canopy, it’s rounded at the top! 90% easy! Don’t look too close, we’re holding up the grinder queue!"',
    truckBedVisual: {
      texture: 'logs_leaves',
      hasHollowPockets: true,
      hasWaterPuddles: false,
      apparentFill: 90,
      trueFill: 45,
    },
    timeLimitSec: 25,
    value: 7200,
  },
  {
    id: 'disp-3',
    ticketBarcode: 'TKT-00000-NONE',
    truckPlacard: 'TRK-999 (Unmarked Red Dump)',
    declaredDebris: 'C&D',
    originVerified: false, // GHOST TRUCK!
    actualDebrisType: 'C&D',
    actualFillLevel: 80,
    isHaulingAir: false,
    isWaterWeight: false,
    driverClaimPercent: 85,
    driverDialogue: 'Driver: "Lost my collection receipt from the field monitor, but you see my bed full of drywall and rafters! Just print me a replacement ticket!"',
    truckBedVisual: {
      texture: 'concrete_drywall',
      hasHollowPockets: false,
      hasWaterPuddles: false,
      apparentFill: 80,
      trueFill: 80,
    },
    timeLimitSec: 20,
    value: 12000,
  },
  {
    id: 'disp-4',
    ticketBarcode: 'TKT-77814-ROW',
    truckPlacard: 'TRK-302 (Steel End Dump 40 CY)',
    declaredDebris: 'C&D',
    originVerified: true,
    actualDebrisType: 'C&D',
    actualFillLevel: 70,
    isHaulingAir: false,
    isWaterWeight: true, // WATER WEIGHT FRAUD!
    driverClaimPercent: 95,
    driverDialogue: 'Driver: "Heavy ton load here! Scale says max gross tonnage! Stamp 95% right away so we can dump!" (Notice: Black water streams pouring from tailgate cracks)',
    truckBedVisual: {
      texture: 'concrete_drywall',
      hasHollowPockets: false,
      hasWaterPuddles: true,
      apparentFill: 85,
      trueFill: 65,
    },
    timeLimitSec: 22,
    value: 9500,
  },
  {
    id: 'disp-5',
    ticketBarcode: 'TKT-31290-ROW',
    truckPlacard: 'TRK-114 (Tandem Axle 30 CY)',
    declaredDebris: 'HHW',
    originVerified: true,
    actualDebrisType: 'HHW',
    actualFillLevel: 60,
    isHaulingAir: false,
    isWaterWeight: false,
    driverClaimPercent: 60,
    driverDialogue: 'Driver: "Household Hazardous Waste containers, secure drums and paint cans. Ready for TDSR HazMat staging inspection."',
    truckBedVisual: {
      texture: 'chemical_drums',
      hasHollowPockets: false,
      hasWaterPuddles: false,
      apparentFill: 60,
      trueFill: 60,
    },
    timeLimitSec: 22,
    value: 5800,
  },
];

export const LHS_SCENARIOS: LHSScenario[] = [
  {
    id: 'lhs-1',
    miniGame: 'find_hanger',
    title: 'Canopy Scan: Find the Dangerous Hanger',
    description: 'You are walking under an oak canopy over Elm Avenue. Locate and tap the broken hanging branch lodged in the upper canopy before the crew speeds by.',
    hazardDescription: 'FEMA only reimburses hangers threatening public Right-of-Way. Identify the suspended limb.',
    data: {
      targets: [
        { id: 't1', x: 28, y: 35, radius: 24, isHanger: false },
        { id: 't2', x: 62, y: 22, radius: 30, isHanger: true }, // Correct hanger!
        { id: 't3', x: 80, y: 55, radius: 22, isHanger: false },
        { id: 't4', x: 42, y: 70, radius: 25, isHanger: false },
      ],
    },
    crewPressureText: 'Sawyer Boss: "Hurry up! Bucket truck boom is running hot at $280/hour! Find the hanger or we drive!"',
    timeLimitSec: 12,
    femaValue: 3200,
  },
  {
    id: 'lhs-2',
    miniGame: 'measure_hanger',
    title: 'Caliper Inspection: Measure the Hanger Break',
    description: 'A broken limb is dangling 25 feet above the road. Zoom in with your digital calipers to check if the diameter at the break point meets FEMA criteria (>= 2 inches) and hangs over eligible public ROW.',
    hazardDescription: 'Rule: Hangers under 2 inches diameter at the point of break are deemed ordinary yard debris or routine maintenance, NOT eligible for FEMA PA unit-rate cutting!',
    data: {
      diameterInches: 3.4, // >= 2 inches -> Eligible!
      overPublicROW: true,
      threatensImprovedProperty: true,
    },
    crewPressureText: 'Sawyer: "Look at it! It’s huge! Give us the cut code so we can charge the municipality $175!"',
    timeLimitSec: 18,
    femaValue: 4200,
  },
  {
    id: 'lhs-3',
    miniGame: 'measure_hanger',
    title: 'Caliper Inspection: Fragile Twig Hanger Trap',
    description: 'A thin snapped pine branch is suspended over the sidewalk. Measure the diameter at the break point.',
    hazardDescription: 'If diameter is < 2 inches, you MUST REJECT. Paying for twig cuts causes immediate FEMA de-obligation and audit penalties!',
    data: {
      diameterInches: 1.3, // < 2 inches -> Ineligible!
      overPublicROW: true,
      threatensImprovedProperty: false,
    },
    crewPressureText: 'Sawyer: "It’s over the sidewalk! A baby could get scratched! Mark it eligible!"',
    timeLimitSec: 18,
    femaValue: 2800,
  },
  {
    id: 'lhs-4',
    miniGame: 'judge_leaner',
    title: 'Protractor & DBH: The 30° / 6" Rule',
    description: 'A tall Slash Pine is leaning toward Maple Street. Measure lean angle from true vertical with your electronic protractor and check DBH (Diameter at Breast Height).',
    hazardDescription: 'FEMA Criterion: A leaner is eligible if lean is > 30 degrees OR trunk is split exposing heartwood, AND DBH is > 6 inches on public ROW.',
    data: {
      leanDegrees: 36, // > 30 deg -> Pass
      dbhInches: 14.5, // > 6 in -> Pass
      onPrivateProperty: false,
      hasROE: false,
    },
    crewPressureText: 'Contractor: "36 degree tilt right into the power lines! That’s an immediate hazard cut!"',
    timeLimitSec: 20,
    femaValue: 6500,
  },
  {
    id: 'lhs-5',
    miniGame: 'judge_leaner',
    title: 'Protractor & DBH: The Shallow Lean Trap',
    description: 'An old sweetgum tree is tilting slightly. Measure the angle and diameter. Sawyer wants to cut down the entire 60-foot tree.',
    hazardDescription: 'Angle is only 18 degrees (must exceed 30 degrees). Not an immediate failure threat.',
    data: {
      leanDegrees: 18, // < 30 deg -> Ineligible!
      dbhInches: 16.0,
      onPrivateProperty: false,
      hasROE: false,
    },
    crewPressureText: 'Sawyer: "It’s leaning! Every tree leans in Florida! Just approve the full takedown fee ($950)!"',
    timeLimitSec: 20,
    femaValue: 4900,
  },
  {
    id: 'lhs-6',
    miniGame: 'csi_wood',
    title: 'CSI Wood: Storm Damage vs Pre-Existing Rot',
    description: 'Inspect the cross-section and trunk damage of a fallen oak tree. Determine whether this is direct disaster impact or pre-existing deferred maintenance rot.',
    hazardDescription: 'FEMA does NOT reimburse pre-existing dead trees, insect-bored heartwood, or hollow decaying trunks!',
    data: {
      damageType: 'decaying_bracket_fungus', // pre-existing rot!
      isStormDamage: false,
    },
    crewPressureText: 'Foreman: "The storm blew it! Who cares if it had mushrooms on the bark? Mark it storm eligible!"',
    timeLimitSec: 16,
    femaValue: 5500,
  },
  {
    id: 'lhs-7',
    miniGame: 'csi_wood',
    title: 'CSI Wood: Fresh Storm Fracture Heartwood',
    description: 'Inspect trunk fracture. White fiber pull, splintered fresh green vascular cambium, no fungal spores.',
    hazardDescription: 'Clean disaster trauma from Cat 4 hurricane wind shear.',
    data: {
      damageType: 'snapped_fresh_heartwood',
      isStormDamage: true,
    },
    crewPressureText: 'Sawyer: "Fresh splintered live oak snapped during 120mph gusts. Valid storm event damage!"',
    timeLimitSec: 16,
    femaValue: 5800,
  },
];

export const CERTIFIER_SCENARIOS: CertifierScenario[] = [
  {
    id: 'cert-1',
    rigType: 'Frameless Dump Trailer',
    isFramelessDump: true, // Strict USACE Safety Ban!
    dimensions: {
      lengthFeet: 34,
      widthFeet: 8,
      heightFeet: 6,
    },
    features: {
      sideboardsValid: false,
      sideboardsHeightInches: 0,
      hasDogHouse: true,
      dogHouseCY: 2.1,
      hasWheelWells: false,
      wheelWellsCY: 0,
      hasChamferedTailgate: true,
      chamferedCY: 1.4,
    },
    licensePlate: 'FL-DMP-9941',
    contractorName: 'QuickHaul Disaster LLC',
    baseCubicYards: 60.4,
    netCertifiedCubicYards: 0, // Must be REJECTED!
  },
  {
    id: 'cert-2',
    rigType: 'Self-Loader (Grapple)',
    isFramelessDump: false,
    dimensions: {
      lengthFeet: 24,
      widthFeet: 8,
      heightFeet: 5.5,
    },
    features: {
      sideboardsValid: true, // +1.0 ft solid wooden sideboards bolted tight
      sideboardsHeightInches: 12,
      hasDogHouse: true, // -1.8 CY
      dogHouseCY: 1.8,
      hasWheelWells: true, // -1.2 CY
      wheelWellsCY: 1.2,
      hasChamferedTailgate: false,
      chamferedCY: 0,
    },
    licensePlate: 'GA-GRP-7720',
    contractorName: 'Apex Recovery Systems',
    baseCubicYards: 39.1,
    netCertifiedCubicYards: 43.2,
  },
  {
    id: 'cert-3',
    rigType: 'Pup Trailer',
    isFramelessDump: false,
    dimensions: {
      lengthFeet: 18,
      widthFeet: 7.5,
      heightFeet: 4.5,
    },
    features: {
      sideboardsValid: false,
      sideboardsHeightInches: 0,
      hasDogHouse: false,
      dogHouseCY: 0,
      hasWheelWells: true,
      wheelWellsCY: 1.1,
      hasChamferedTailgate: true,
      chamferedCY: 0.9,
    },
    licensePlate: 'TX-PUP-3184',
    contractorName: 'Bayou Hauling Corp',
    baseCubicYards: 22.5,
    netCertifiedCubicYards: 20.5,
  },
  {
    id: 'cert-4',
    rigType: 'Box Truck',
    isFramelessDump: false,
    dimensions: {
      lengthFeet: 26,
      widthFeet: 8,
      heightFeet: 8,
    },
    features: {
      sideboardsValid: false,
      sideboardsHeightInches: 0,
      hasDogHouse: false,
      dogHouseCY: 0,
      hasWheelWells: true,
      wheelWellsCY: 2.2,
      hasChamferedTailgate: false,
      chamferedCY: 0,
    },
    licensePlate: 'NC-BOX-5501',
    contractorName: 'Disaster Express Transport',
    baseCubicYards: 61.6,
    netCertifiedCubicYards: 59.4,
  },
];
